x= int(input())
l=len(bin(x))
for i in range(1,x+1):
    print(str(i).rjust(l," "),end="")
    oc=oct(i)
    stripped1=oc.lstrip('0o')
    print (stripped1.rjust(l,' '),end="")
    he= hex(i)
    stripped2=he.lstrip('0x')
    print( stripped2.rjust(l,' '),end="")
    bi = bin(i)
    stripped3 = bi.lstrip('0b')
    print( stripped3.rjust(l,' '))
    #print("welcome".rjust(22,'-'))